name: Provision (Initial Setup)

on:
  workflow_dispatch:

jobs:
  provision:
    name: Initial Deploy to SOLCloud
    uses: LMCustoms/.github/.github/workflows/deploy-ssh.yml@main
    with:
      script: |
        cd /home/anian/neo-dock
        curl -fsSL https://raw.githubusercontent.com/LMCustoms/neo-dock/main/docker-compose.yml -o docker-compose.yml
        echo "$GHCR_TOKEN" | docker login ghcr.io -u LMCustoms --password-stdin
        docker compose pull
        docker compose up -d --force-recreate
        docker image prune -f
        docker logout ghcr.io
    secrets:
      DEPLOY_HOST: ${{ secrets.HOST }}
      DEPLOY_USER: ${{ secrets.USER }}
      DEPLOY_SSH_KEY: ${{ secrets.SSH_KEY }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
